[variables]
FLUTTER_VERSION = "3.32.0"

[phases.setup]
nixPkgs = ["flutter"]

[phases.build]
commands = [
  "flutter --version",
  "flutter pub get",
  "flutter build web"
]

[start]
command = "python3 -m http.server $PORT --directory build/web"