name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.8.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_nombre.png
    - assets/videos/bg_drone.mp4
    - assets/logo_sin_fondo.png
    - assets/logonom_sin_fondo.png